### ISSUE TITLE
Docker-compose file should include default configuration as environment variables

### ISSUE THREAD

**Issue by flavienbwk** [prologic/twtxt#33]
Hi,

Currently, the documentation states the following : 

```console
./twtd -h
Usage of ./twtd:
  -u, --base-url string           base url to use (default "http://0.0.0.0:8000")
  -b, --bind string               [int]:<port> to bind to (default "0.0.0.0:8000")
  -S, --cookie-secret string      cookie secret to use (default "PLEASE_CHANGE_ME!!!")
  -d, --data string               data directory (default "./data")
  -D, --debug                     enable debug logging
  -F, --feed-sources strings      external feed sources (default [https://feeds.twtxt.net/we-are-feeds.txt,https://raw.githubusercontent.com/mdom/we-are-twtxt/master/we-are-bots.txt])
  -L, --max-tweet-length int      maximum length of posts (default 288)
  -n, --name string               set the instance's name (default "twtxt.net")
  -r, --register                  enable user registration
  -E, --session-expiry duration   session expiry to use (default 24h0m0s)
  -s, --store string              store to use (default "bitcask://twtxt.db")
  -t, --theme string              set the default theme (default "dark")
  -T, --tweets-per-page int       tweets per page to display (default 50)
  -v, --version                   display version information
pflag: help requested
```

It might be useful to have these options (or at least the most important) as environment variables in docker-compose, as they can't be run without : 

```yml
version: '3'

services:

    twtxt:
        build: .
        ports:
            - 8000:8000
        volumes:
            - ./data:/data
        environment: 
            NAME: "twtxt.net"
            BASE_URL: "http://0.0.0.0:8000"
            BIND: "0.0.0.0:8000"
            COOKIE_SECRET: "PLEASE_CHANGE_ME_TO_A_64_BYTE_RANDOM_STRING"
            REGISTER: "true"
            DEBUG: "false"
            THEME: "dark"
            MAX_TWEET_LENGTH: 288
            TWEETS_PER_PAGE: 50
```

What is your opinion ?

I already tested that, it's working well. 

------

May be an answer for #29
